# Generated by Django 5.2.3 on 2025-06-30 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolcanicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('seismic_activity', models.FloatField(help_text='Magnitude of seismic activity')),
                ('gas_emissions', models.FloatField(help_text='SO2 levels in ppm')),
                ('ground_deformation', models.FloatField(help_text='Ground movement in mm')),
                ('temperature', models.FloatField(help_text='Crater temperature in Celsius')),
                ('alert_level', models.CharField(choices=[('green', 'Green - Normal'), ('yellow', 'Yellow - Advisory'), ('orange', 'Orange - Watch'), ('red', 'Red - Warning')], default='green', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
